dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.8-dev
    - python: nightly

install:
  - pip install setuptools pytest pytest-cov flake8 python-coveralls
  - if [ $(python -c "import sys; sys.exit(1 if (sys.version_info >= (3, 5)) else 0)") -eq 1 ]; then pip install flake8-bugbear; fi

script:
  - flake8
  - python3 setup.py test

after_success:
  - coveralls
